// Generated by tools/generate-launcher-assets.py. Layout is in device pixels.
#pragma once
#include <stdint.h>
#include <stddef.h>
namespace apps {
enum class Id : uint8_t { Pet, Steady, Vibe, Sonifier, TapTap };
enum class Availability : uint8_t { Ready, Preview, Planned };
struct Rect { int16_t x, y, w, h; };
struct Ellipse { int16_t cx, cy, rx, ry; };
struct Manifest { Id id; const char* label; Availability availability; Rect art; Ellipse hit; uint16_t accent; };
static constexpr size_t kAppCount = 5;
static constexpr Manifest kApps[kAppCount] = {
    {Id::Pet, "Pet", Availability::Ready, {72,68,174,174}, {159,155,80,80}, 0xfb6d},
    {Id::Steady, "Steady", Availability::Preview, {254,73,145,142}, {326,144,65,64}, 0xa7e8},
    {Id::Vibe, "Vibe", Availability::Planned, {291,226,145,148}, {363,300,64,66}, 0x07bf},
    {Id::Sonifier, "Sonifier", Availability::Planned, {33,244,143,142}, {104,315,64,64}, 0xbb5f},
    {Id::TapTap, "Tap Tap", Availability::Planned, {174,316,149,129}, {248,380,67,54}, 0xfd86},
};
} // namespace apps
