#pragma once
// Build-time configuration (NOT secrets). Edit and rebuild.

#ifndef PROXY_URL
// Cloudflare worker URL (HTTPS). Keep only local-only LAN URL here for local fallback.
// For staging/prod, flash the matching firmware build that points to that worker URL.
#define PROXY_URL "https://tokengochi-staging.example.workers.dev"
#endif

#ifndef POLL_INTERVAL_MS
#define POLL_INTERVAL_MS 300000  // how often to GET /pet/state
#endif

#ifndef TOKENGOCHI_PASSIVE_POLL_INTERVAL_MS
#define TOKENGOCHI_PASSIVE_POLL_INTERVAL_MS 600000  // asleep/passive idle state polling
#endif

#ifndef TOKENGOCHI_CPU_MHZ
#define TOKENGOCHI_CPU_MHZ 80
#endif

#ifndef TOKENGOCHI_SLEEP_CPU_MHZ
#define TOKENGOCHI_SLEEP_CPU_MHZ TOKENGOCHI_CPU_MHZ
#endif

#ifndef TOKENGOCHI_IDLE_LOOP_DELAY_MS
#define TOKENGOCHI_IDLE_LOOP_DELAY_MS 100
#endif

#ifndef TOKENGOCHI_ACTIVE_LOOP_DELAY_MS
#define TOKENGOCHI_ACTIVE_LOOP_DELAY_MS 20
#endif

#ifndef TOKENGOCHI_SLEEP_LOOP_DELAY_MS
#define TOKENGOCHI_SLEEP_LOOP_DELAY_MS 1000
#endif

#ifndef TOKENGOCHI_PASSIVE_LIGHT_SLEEP_MS
#define TOKENGOCHI_PASSIVE_LIGHT_SLEEP_MS 5000
#endif

#ifndef TOKENGOCHI_LIGHT_SLEEP
#define TOKENGOCHI_LIGHT_SLEEP 1
#endif

#ifndef TOKENGOCHI_LIGHT_SLEEP_WHEN_SERIAL_CONNECTED
#define TOKENGOCHI_LIGHT_SLEEP_WHEN_SERIAL_CONNECTED 1
#endif

#ifndef TOKENGOCHI_LIGHT_SLEEP_MIN_MS
#define TOKENGOCHI_LIGHT_SLEEP_MIN_MS 200
#endif

#ifndef TOKENGOCHI_SERIAL_WAKEUP_EDGES
#define TOKENGOCHI_SERIAL_WAKEUP_EDGES 3
#endif

#ifndef TOKENGOCHI_SERIAL_WAKE_AWAKE_MS
#define TOKENGOCHI_SERIAL_WAKE_AWAKE_MS 2500
#endif

#ifndef TOKENGOCHI_DISPLAY_SLEEP_MS
#define TOKENGOCHI_DISPLAY_SLEEP_MS 30000
#endif

#ifndef TOKENGOCHI_BATTERY_SAMPLE_MS
#define TOKENGOCHI_BATTERY_SAMPLE_MS 300000
#endif

#ifndef TOKENGOCHI_WIFI_RECONNECT_MS
#define TOKENGOCHI_WIFI_RECONNECT_MS 60000
#endif

#ifndef TOKENGOCHI_WIFI_SLEEP_RECONNECT_MS
#define TOKENGOCHI_WIFI_SLEEP_RECONNECT_MS 300000
#endif

#ifndef TOKENGOCHI_WIFI_IDLE_OFF_MS
#define TOKENGOCHI_WIFI_IDLE_OFF_MS 15000
#endif

#ifndef TOKENGOCHI_WIFI_CONNECT_TIMEOUT_MS
#define TOKENGOCHI_WIFI_CONNECT_TIMEOUT_MS 10000
#endif

#ifndef TOKENGOCHI_WIFI_DIRECT_CONNECT_TIMEOUT_MS
#define TOKENGOCHI_WIFI_DIRECT_CONNECT_TIMEOUT_MS 6000
#endif

#ifndef TOKENGOCHI_WIFI_TX_POWER
#define TOKENGOCHI_WIFI_TX_POWER WIFI_POWER_8_5dBm
#endif

#ifndef TOKENGOCHI_BLINK_PERIOD_MS
#define TOKENGOCHI_BLINK_PERIOD_MS 3000
#endif

#ifndef HTTP_TIMEOUT_MS
#define HTTP_TIMEOUT_MS 8000     // HTTPClient.setTimeout
#endif

#ifndef TRANSCRIBE_TIMEOUT_MS
#define TRANSCRIBE_TIMEOUT_MS 30000  // Cloudflare -> Groq can take a few seconds
#endif

#ifndef TRANSCRIPT_LOG_RETENTION_DAYS
#define TRANSCRIPT_LOG_RETENTION_DAYS 7
#endif

#ifndef TRANSCRIPT_LOG_MAX_ENTRIES
#define TRANSCRIPT_LOG_MAX_ENTRIES 30
#endif

#ifndef TRANSCRIPT_LOG_TEXT_BYTES
#define TRANSCRIPT_LOG_TEXT_BYTES 512
#endif

#ifndef TRANSCRIPT_LOG_LANG_BYTES
#define TRANSCRIPT_LOG_LANG_BYTES 12
#endif

#ifndef TOKENGOCHI_COMPACT_UI
#define TOKENGOCHI_COMPACT_UI 0
#endif

#if defined(TOKENGOCHI_DEVICE_M5STICKC_PLUS2)
#define TOKENGOCHI_DEVICE_NAME "M5StickC Plus2"
#define TOKENGOCHI_HAS_TOUCH 0
#define TOKENGOCHI_HAS_VIBRATION 0
#define TOKENGOCHI_HOME_PET_SCALE 1
// M5StickC Plus2 is rendered landscape after M5.Display.setRotation(1).
#define SCREEN_W      240
#define SCREEN_H      135
#define SCREEN_R      67
#else
#define TOKENGOCHI_DEVICE_NAME "M5Stack StopWatch"
#define TOKENGOCHI_HAS_TOUCH 1
#define TOKENGOCHI_HAS_VIBRATION 1
#define TOKENGOCHI_HOME_PET_SCALE 2
// Round AMOLED is 466x466 with a ~233 px visible radius. We clip drawing
// to the inscribed circle so nothing leaks into the chassis corners.
#define SCREEN_W      466
#define SCREEN_H      466
#define SCREEN_R      233
#endif

#define SCREEN_CX     (SCREEN_W / 2)
#define SCREEN_CY     (SCREEN_H / 2)
