#!/usr/bin/env python3
"""Generate firmware RGB565/paletted RLE artwork from the supplied reference.
Development-only dependency: Pillow. Generated firmware needs no image library.
Usage: python3 tools/generate-launcher-assets.py path/to/reference.png
"""
from pathlib import Path
import argparse, json
from PIL import Image, ImageFilter
from collections import deque

ROOT = Path(__file__).resolve().parents[1]
TILES = [
    # id, label, availability, crop, x/y, w/h, hit ellipse cx/cy/rx/ry, accent
    ('Pet', 'Pet', 'Ready', (140,150,625,635), (72,68,174,174), (159,155,80,80), 0xFB6D),
    ('Steady', 'Steady', 'Preview', (687,145,1099,548), (254,73,145,142), (326,144,65,64), 0xA7E8),
    ('Vibe', 'Vibe', 'Planned', (798,522,1204,938), (291,226,145,148), (363,300,64,66), 0x07BF),
    ('Sonifier', 'Sonifier', 'Planned', (75,651,475,1046), (33,244,143,142), (104,315,64,64), 0xBB5F),
    ('TapTap', 'Tap Tap', 'Planned', (509,814,924,1174), (174,316,149,129), (248,380,67,54), 0xFD86),
]

def isolate(tile, index):
    """Keep the tile enclosed by its own accent rim, not neighbouring artwork."""
    w,h=tile.size
    mask=Image.new('L',(w,h)); src=tile.load(); dst=mask.load()
    for y in range(h):
        for x in range(w):
            r,g,b=src[x,y]
            matches=(r>100 and r>1.15*g and r>1.05*b,
                     g>100 and g>1.12*r and g>1.15*b,
                     b>90 and g>75 and b>1.4*r and g>1.4*r,
                     b>90 and r>60 and b>1.15*g,
                     r>120 and g>75 and g<0.9*r and b<0.7*g)
            dst[x,y]=255 if matches[index] else 0
    mask=mask.filter(ImageFilter.MaxFilter(3)); dst=mask.load()
    seen=set(); best=[]; best_area=0
    for y in range(h):
        for x in range(w):
            if not dst[x,y] or (x,y) in seen: continue
            q=deque([(x,y)]); seen.add((x,y)); component=[]
            while q:
                u,v=q.popleft(); component.append((u,v))
                for a,b in ((u-1,v),(u+1,v),(u,v-1),(u,v+1)):
                    if 0<=a<w and 0<=b<h and dst[a,b] and (a,b) not in seen:
                        seen.add((a,b)); q.append((a,b))
            area=(max(c[0] for c in component)-min(c[0] for c in component)+1)*(max(c[1] for c in component)-min(c[1] for c in component)+1)
            if area>best_area: best_area=area; best=component
    silhouette=Image.new('L',(w,h)); rows={}
    for x,y in best: rows.setdefault(y,[]).append(x)
    out=silhouette.load()
    for y,xs in rows.items():
        for x in range(min(xs),max(xs)+1): out[x,y]=255
    silhouette=silhouette.filter(ImageFilter.MaxFilter(5))
    return Image.composite(tile,Image.new('RGB',(w,h)),silhouette)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('reference', type=Path)
    args = parser.parse_args()
    source = Image.open(args.reference).convert('RGB')
    if source.size != (1254,1254):
        raise SystemExit('Expected the original 1254 x 1254 reference, not a rescaled copy.')
    images = []
    clipped = 0
    for index, (_, _, _, crop, rect, _, _) in enumerate(TILES):
        x,y,w,h = rect
        tile = isolate(source.crop(crop).resize((w,h), Image.Resampling.NEAREST),index)
        pixels = tile.load()
        for v in range(h):
            for u in range(w):
                if (x+u-233)**2 + (y+v-233)**2 > 233**2:
                    clipped += int(max(pixels[u,v]) > 32)
                    pixels[u,v] = (0,0,0)
                elif max(pixels[u,v]) < 20:
                    pixels[u,v] = (0,0,0)
        images.append(tile)
    images.append(source.crop((220,276,550,516)).resize((110,80), Image.Resampling.NEAREST))
    atlas = Image.new('RGB',(sum(i.width for i in images), max(i.height for i in images)))
    offset = 0
    for tile in images:
        atlas.paste(tile,(offset,0)); offset += tile.width
    indexed = atlas.quantize(colors=128, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    palette = indexed.getpalette()[:384]
    rgbs = [tuple(palette[i:i+3]) for i in range(0,384,3)]
    black = min(range(128), key=lambda i: sum(rgbs[i]))
    order = [black] + [i for i in range(128) if i != black]
    remap = {old: new for new,old in enumerate(order)}
    p565 = [0] + [((rgbs[i][0]>>3)<<11)|((rgbs[i][1]>>2)<<5)|(rgbs[i][2]>>3) for i in order[1:]]
    chunks = ['// Generated by tools/generate-launcher-assets.py. Do not edit.\n#pragma once\n#include <stdint.h>\nnamespace apps { namespace art {\nstruct Asset { uint16_t width, height; const uint8_t* runs; uint32_t bytes; };\n']
    chunks.append('static const uint16_t palette[128] = {\n' + ',\n'.join('  '+','.join(f'0x{v:04x}' for v in p565[j:j+16]) for j in range(0,128,16)) + '\n};\n')
    offset = 0
    total = 256
    lengths=[]
    for k,img in enumerate(images):
        tile = indexed.crop((offset,0,offset+img.width,img.height)); offset += img.width
        values = [remap[v] for v in tile.tobytes()]
        rle=[]
        for row in range(img.height):
            data=values[row*img.width:(row+1)*img.width]
            i=0
            while i<len(data):
                n=1
                while i+n<len(data) and data[i+n]==data[i] and n<255: n+=1
                rle.extend((n,data[i])); i+=n
        total += len(rle); lengths.append(len(rle))
        chunks.append(f'static const uint8_t runs{k}[] = {{\n' + ',\n'.join('  '+','.join(str(v) for v in rle[j:j+40]) for j in range(0,len(rle),40)) + '\n};\n')
    chunks.append('static const Asset assets[] = {\n'+',\n'.join(f'  {{{i.width},{i.height},runs{k},sizeof(runs{k})}}' for k,i in enumerate(images))+'\n};\n}} // namespace apps::art\n')
    (ROOT/'firmware/src/app_launcher_assets.h').write_text(''.join(chunks))
    manifest='''// Generated by tools/generate-launcher-assets.py. Layout is in device pixels.
#pragma once
#include <stdint.h>
#include <stddef.h>
namespace apps {
enum class Id : uint8_t { Pet, Steady, Vibe, Sonifier, TapTap };
enum class Availability : uint8_t { Ready, Preview, Planned };
struct Rect { int16_t x, y, w, h; };
struct Ellipse { int16_t cx, cy, rx, ry; };
struct Manifest { Id id; const char* label; Availability availability; Rect art; Ellipse hit; uint16_t accent; };
static constexpr size_t kAppCount = 5;
static constexpr Manifest kApps[kAppCount] = {
'''
    for ident,label,status,crop,rect,hit,color in TILES:
        manifest+=f'    {{Id::{ident}, "{label}", Availability::{status}, {{{",".join(map(str,rect))}}}, {{{",".join(map(str,hit))}}}, 0x{color:04x}}},\n'
    manifest+='};\n} // namespace apps\n'
    (ROOT/'firmware/src/app_launcher_manifest.h').write_text(manifest)
    report={'source_size':list(source.size),'palette_bytes':256,'rle_bytes':lengths,'total_palette_and_rle_bytes':total,'bright_pixels_outside_disc_removed':clipped,'tiles':[{'id':t[0],'rect':t[4],'hit':t[5],'availability':t[2]} for t in TILES]}
    (ROOT/'docs/launcher-assets.json').write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps(report,indent=2))

if __name__=='__main__': main()
